"""Narrative Engine orchestrator for Story Intelligence."""
import logging
from typing import List, Dict, Any, Optional

from .hook_generator import HookGenerator
from .pacing_controller import PacingController
from .scene_optimizer import SceneOptimizer

logger = logging.getLogger(__name__)

class NarrativeEngine:
    """Orchestrates story optimization, rewriting hooks, and formatting visual styles."""
    
    def __init__(self):
        self.hook_generator = HookGenerator()
        self.pacing_controller = PacingController()
        self.scene_optimizer = SceneOptimizer()
        
    def optimize_script(self, scenes: List[Dict[str, Any]], visual_style: str = "tiktok_native", target_duration: float = 30.0) -> List[Dict[str, Any]]:
        """Improve a full list of scenes (voiceover text, visual prompts, and scene durations) for high retention.
        
        Args:
            scenes: Initial scenes generated by Gemini.
            visual_style: The visual style (e.g. CCTV, Cinematic, Horror).
            target_duration: Target video duration.
            
        Returns:
            Optimized list of scenes.
        """
        logger.info("Starting NarrativeEngine script optimization workflow...")
        if not scenes:
            return []
            
        # 1. Rewrite hook in the first scene
        first_scene = scenes[0]
        original_text = first_scene.get("text", "")
        
        # We only rewrite if the hook isn't already super strong (heuristics checking)
        from app.services.viral.hook_analyzer import HookAnalyzer
        analyzer = HookAnalyzer()
        hook_res = analyzer.analyze_hook(original_text)
        
        optimized_scenes = [dict(s) for s in scenes]
        if hook_res["hook_score"] < 0.6:
            logger.info("Hook is weak. Applying automated hook rewriting...")
            viral_hook = self.hook_generator.rewrite_opening(original_text)
            optimized_scenes[0]["text"] = viral_hook
            
        # 2. Apply Pacing timings and dramatic pauses
        optimized_scenes = self.pacing_controller.optimize_timings(optimized_scenes, target_duration)
        
        # 3. Apply Style prompt modifiers and clean speech fillers
        optimized_scenes = self.scene_optimizer.optimize_scenes(optimized_scenes, visual_style)
        
        return optimized_scenes
