"""Add Phase 7.1 fields to TrendingTopic

Revision ID: 0c82757605bb
Revises: b67521fde85a
Create Date: 2026-05-23 14:59:57.181154

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '0c82757605bb'
down_revision: Union[str, None] = 'b67521fde85a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trending_topic', sa.Column('velocity_score', sa.Float(), nullable=False, server_default='0.0'))
    op.add_column('trending_topic', sa.Column('reuse_count', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('trending_topic', sa.Column('format_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('trending_topic', sa.Column('last_seen', sa.DateTime(), nullable=False, server_default=sa.func.now()))
    op.add_column('user_settings', sa.Column('preferred_video_backend', sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default='auto'))
    op.add_column('user_settings', sa.Column('video_quality', sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default='1080p'))
    op.add_column('user_settings', sa.Column('max_ai_video_duration', sa.Float(), nullable=False, server_default='60.0'))
    op.add_column('user_settings', sa.Column('hybrid_rendering', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('user_settings', sa.Column('motion_intensity', sa.Float(), nullable=False, server_default='0.5'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_settings', 'motion_intensity')
    op.drop_column('user_settings', 'hybrid_rendering')
    op.drop_column('user_settings', 'max_ai_video_duration')
    op.drop_column('user_settings', 'video_quality')
    op.drop_column('user_settings', 'preferred_video_backend')
    op.drop_column('trending_topic', 'last_seen')
    op.drop_column('trending_topic', 'format_type')
    op.drop_column('trending_topic', 'reuse_count')
    op.drop_column('trending_topic', 'velocity_score')
    # ### end Alembic commands ###
