"""Add Phase 8 Orchestration Models

Revision ID: 2e9753f7794a
Revises: ab7b7abc12c9
Create Date: 2026-05-23 15:29:25.585659

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2e9753f7794a'
down_revision: Union[str, None] = 'ab7b7abc12c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_memory_record',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('agent_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('state', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('recent_decisions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('recent_errors', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_memory_record_agent_name'), 'agent_memory_record', ['agent_name'], unique=False)
    op.create_table('campaign',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('total_episodes', sa.Integer(), nullable=False),
    sa.Column('current_episode', sa.Integer(), nullable=False),
    sa.Column('storyline_persistence', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('recurring_characters', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campaign_name'), 'campaign', ['name'], unique=False)
    op.create_table('content_schedule',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('platform', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('publish_time', sa.DateTime(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('trend_topic', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('predicted_score', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_content_schedule_platform'), 'content_schedule', ['platform'], unique=False)
    op.create_index(op.f('ix_content_schedule_status'), 'content_schedule', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_content_schedule_status'), table_name='content_schedule')
    op.drop_index(op.f('ix_content_schedule_platform'), table_name='content_schedule')
    op.drop_table('content_schedule')
    op.drop_index(op.f('ix_campaign_name'), table_name='campaign')
    op.drop_table('campaign')
    op.drop_index(op.f('ix_agent_memory_record_agent_name'), table_name='agent_memory_record')
    op.drop_table('agent_memory_record')
    # ### end Alembic commands ###
