"""Add Phase 7.2 Autonomous Learning Models

Revision ID: ab7b7abc12c9
Revises: 0c82757605bb
Create Date: 2026-05-23 15:18:49.340329

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'ab7b7abc12c9'
down_revision: Union[str, None] = '0c82757605bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hook_template',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('template_text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('emotion', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('usage_count', sa.Integer(), nullable=False),
    sa.Column('success_rate', sa.Float(), nullable=False),
    sa.Column('last_used', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('style_performance',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('style_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('platform', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('usage_count', sa.Integer(), nullable=False),
    sa.Column('success_rate', sa.Float(), nullable=False),
    sa.Column('last_used', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_style_performance_platform'), 'style_performance', ['platform'], unique=False)
    op.create_index(op.f('ix_style_performance_style_name'), 'style_performance', ['style_name'], unique=False)
    op.create_table('viral_pattern',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('pattern_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('pattern_data', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('usage_count', sa.Integer(), nullable=False),
    sa.Column('success_rate', sa.Float(), nullable=False),
    sa.Column('last_used', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_viral_pattern_pattern_type'), 'viral_pattern', ['pattern_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_viral_pattern_pattern_type'), table_name='viral_pattern')
    op.drop_table('viral_pattern')
    op.drop_index(op.f('ix_style_performance_style_name'), table_name='style_performance')
    op.drop_index(op.f('ix_style_performance_platform'), table_name='style_performance')
    op.drop_table('style_performance')
    op.drop_table('hook_template')
    # ### end Alembic commands ###
