"""phase_4_viral_intelligence

Revision ID: b67521fde85a
Revises: bd5aeceedc0a
Create Date: 2026-05-22 22:46:43.570379

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b67521fde85a'
down_revision: Union[str, None] = 'bd5aeceedc0a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
