"""add_viral_intelligence_models

Revision ID: bd5aeceedc0a
Revises: ebe3bf76544b
Create Date: 2026-05-22 19:31:04.583285

"""
from typing import Sequence, Union
import sqlmodel

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bd5aeceedc0a'
down_revision: Union[str, None] = 'ebe3bf76544b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clip_analysis',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('source_video_path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('clip_path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('start_time', sa.Float(), nullable=False),
    sa.Column('end_time', sa.Float(), nullable=False),
    sa.Column('highlight_score', sa.Float(), nullable=False),
    sa.Column('transcript', sa.Text(), nullable=False),
    sa.Column('emotional_tone', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clip_analysis_created_at'), 'clip_analysis', ['created_at'], unique=False)
    op.create_table('content_embedding',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=False),
    sa.Column('entity_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('vector_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('extra_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_content_embedding_created_at'), 'content_embedding', ['created_at'], unique=False)
    op.create_index(op.f('ix_content_embedding_entity_id'), 'content_embedding', ['entity_id'], unique=False)
    op.create_index(op.f('ix_content_embedding_entity_type'), 'content_embedding', ['entity_type'], unique=False)
    op.create_table('trending_topic',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('topic', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('virality_score', sa.Float(), nullable=False),
    sa.Column('momentum_score', sa.Float(), nullable=False),
    sa.Column('engagement_rate', sa.Float(), nullable=False),
    sa.Column('hook_patterns', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('related_hashtags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('pacing_style', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('visual_style', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trending_topic_category'), 'trending_topic', ['category'], unique=False)
    op.create_index(op.f('ix_trending_topic_created_at'), 'trending_topic', ['created_at'], unique=False)
    op.create_index(op.f('ix_trending_topic_topic'), 'trending_topic', ['topic'], unique=False)
    op.create_table('video_performance_metrics',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('video_id', sa.Uuid(), nullable=False),
    sa.Column('views', sa.Integer(), nullable=False),
    sa.Column('likes', sa.Integer(), nullable=False),
    sa.Column('shares', sa.Integer(), nullable=False),
    sa.Column('comments', sa.Integer(), nullable=False),
    sa.Column('average_watch_time', sa.Float(), nullable=False),
    sa.Column('retention_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ctr', sa.Float(), nullable=False),
    sa.Column('platform', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['video_id'], ['video.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_video_performance_metrics_video_id'), 'video_performance_metrics', ['video_id'], unique=False)
    op.create_table('viral_analysis',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('video_id', sa.Uuid(), nullable=True),
    sa.Column('script_text', sa.Text(), nullable=False),
    sa.Column('hook_strength', sa.Float(), nullable=False),
    sa.Column('retention_probability', sa.Float(), nullable=False),
    sa.Column('pacing_score', sa.Float(), nullable=False),
    sa.Column('emotional_intensity', sa.Float(), nullable=False),
    sa.Column('curiosity_gap', sa.Float(), nullable=False),
    sa.Column('trend_alignment', sa.Float(), nullable=False),
    sa.Column('overall_score', sa.Float(), nullable=False),
    sa.Column('recommendations', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['video_id'], ['video.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_viral_analysis_created_at'), 'viral_analysis', ['created_at'], unique=False)
    op.create_index(op.f('ix_viral_analysis_video_id'), 'viral_analysis', ['video_id'], unique=False)
    op.create_index(op.f('ix_channel_user_id'), 'channel', ['user_id'], unique=False)
    op.create_foreign_key(None, 'channel', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'channel', type_='foreignkey')
    op.drop_index(op.f('ix_channel_user_id'), table_name='channel')
    op.drop_index(op.f('ix_viral_analysis_video_id'), table_name='viral_analysis')
    op.drop_index(op.f('ix_viral_analysis_created_at'), table_name='viral_analysis')
    op.drop_table('viral_analysis')
    op.drop_index(op.f('ix_video_performance_metrics_video_id'), table_name='video_performance_metrics')
    op.drop_table('video_performance_metrics')
    op.drop_index(op.f('ix_trending_topic_topic'), table_name='trending_topic')
    op.drop_index(op.f('ix_trending_topic_created_at'), table_name='trending_topic')
    op.drop_index(op.f('ix_trending_topic_category'), table_name='trending_topic')
    op.drop_table('trending_topic')
    op.drop_index(op.f('ix_content_embedding_entity_type'), table_name='content_embedding')
    op.drop_index(op.f('ix_content_embedding_entity_id'), table_name='content_embedding')
    op.drop_index(op.f('ix_content_embedding_created_at'), table_name='content_embedding')
    op.drop_table('content_embedding')
    op.drop_index(op.f('ix_clip_analysis_created_at'), table_name='clip_analysis')
    op.drop_table('clip_analysis')
    # ### end Alembic commands ###
