"""Add PipelineState and scene_progress to GeneratedVideo

Revision ID: ebe3bf76544b
Revises: 4ec356ef86c0
Create Date: 2026-05-22 17:45:33.344380

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.

revision: str = 'ebe3bf76544b'
down_revision: Union[str, None] = '4ec356ef86c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Removing accidental drop_table commands for unimported models
    pipeline_state_enum = postgresql.ENUM('QUEUED', 'SCRIPTING', 'VALIDATED', 'IMAGE_GENERATION', 'AUDIO_GENERATION', 'MEDIA_COMPOSITION', 'ENCODING', 'UPLOADING', 'DONE', 'FAILED', name='pipelinestate')
    pipeline_state_enum.create(op.get_bind())
    op.add_column('video', sa.Column('pipeline_state', pipeline_state_enum, nullable=False, server_default='QUEUED'))
    op.add_column('video', sa.Column('scene_progress', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.alter_column('video', 'progress',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('video', 'progress',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.drop_column('video', 'scene_progress')
    op.drop_column('video', 'pipeline_state')
    # ### end Alembic commands ###
